package com.leo.dao;

import com.leo.domain.Heroes;
import com.leo.domain.HeroesExample;
import java.util.List;
import org.apache.ibatis.annotations.Delete;
import org.apache.ibatis.annotations.DeleteProvider;
import org.apache.ibatis.annotations.Insert;
import org.apache.ibatis.annotations.InsertProvider;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.annotations.Result;
import org.apache.ibatis.annotations.Results;
import org.apache.ibatis.annotations.Select;
import org.apache.ibatis.annotations.SelectProvider;
import org.apache.ibatis.annotations.Update;
import org.apache.ibatis.annotations.UpdateProvider;
import org.apache.ibatis.type.JdbcType;

public interface HeroesMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table heroes
     *
     * @mbg.generated
     */
    @SelectProvider(type=HeroesSqlProvider.class, method="countByExample")
    long countByExample(HeroesExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table heroes
     *
     * @mbg.generated
     */
    @DeleteProvider(type=HeroesSqlProvider.class, method="deleteByExample")
    int deleteByExample(HeroesExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table heroes
     *
     * @mbg.generated
     */
    @Delete({
        "delete from heroes",
        "where id = #{id,jdbcType=INTEGER}"
    })
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table heroes
     *
     * @mbg.generated
     */
    @Insert({
        "insert into heroes (id, name)",
        "values (#{id,jdbcType=INTEGER}, #{name,jdbcType=VARCHAR})"
    })
    int insert(Heroes record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table heroes
     *
     * @mbg.generated
     */
    @InsertProvider(type=HeroesSqlProvider.class, method="insertSelective")
    int insertSelective(Heroes record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table heroes
     *
     * @mbg.generated
     */
    @SelectProvider(type=HeroesSqlProvider.class, method="selectByExample")
    @Results({
        @Result(column="id", property="id", jdbcType=JdbcType.INTEGER, id=true),
        @Result(column="name", property="name", jdbcType=JdbcType.VARCHAR)
    })
    List<Heroes> selectByExample(HeroesExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table heroes
     *
     * @mbg.generated
     */
    @Select({
        "select",
        "id, name",
        "from heroes",
        "where id = #{id,jdbcType=INTEGER}"
    })
    @Results({
        @Result(column="id", property="id", jdbcType=JdbcType.INTEGER, id=true),
        @Result(column="name", property="name", jdbcType=JdbcType.VARCHAR)
    })
    Heroes selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table heroes
     *
     * @mbg.generated
     */
    @UpdateProvider(type=HeroesSqlProvider.class, method="updateByExampleSelective")
    int updateByExampleSelective(@Param("record") Heroes record, @Param("example") HeroesExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table heroes
     *
     * @mbg.generated
     */
    @UpdateProvider(type=HeroesSqlProvider.class, method="updateByExample")
    int updateByExample(@Param("record") Heroes record, @Param("example") HeroesExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table heroes
     *
     * @mbg.generated
     */
    @UpdateProvider(type=HeroesSqlProvider.class, method="updateByPrimaryKeySelective")
    int updateByPrimaryKeySelective(Heroes record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table heroes
     *
     * @mbg.generated
     */
    @Update({
        "update heroes",
        "set name = #{name,jdbcType=VARCHAR}",
        "where id = #{id,jdbcType=INTEGER}"
    })
    int updateByPrimaryKey(Heroes record);
}