package com.leo.domain;

import java.util.ArrayList;
import java.util.List;

public class AccountExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table ACCOUNT
     *
     * @mbg.generated
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table ACCOUNT
     *
     * @mbg.generated
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table ACCOUNT
     *
     * @mbg.generated
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ACCOUNT
     *
     * @mbg.generated
     */
    public AccountExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ACCOUNT
     *
     * @mbg.generated
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ACCOUNT
     *
     * @mbg.generated
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ACCOUNT
     *
     * @mbg.generated
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ACCOUNT
     *
     * @mbg.generated
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ACCOUNT
     *
     * @mbg.generated
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ACCOUNT
     *
     * @mbg.generated
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ACCOUNT
     *
     * @mbg.generated
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ACCOUNT
     *
     * @mbg.generated
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ACCOUNT
     *
     * @mbg.generated
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ACCOUNT
     *
     * @mbg.generated
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table ACCOUNT
     *
     * @mbg.generated
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andIdIsNull() {
            addCriterion("ID is null");
            return (Criteria) this;
        }

        public Criteria andIdIsNotNull() {
            addCriterion("ID is not null");
            return (Criteria) this;
        }

        public Criteria andIdEqualTo(Integer value) {
            addCriterion("ID =", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotEqualTo(Integer value) {
            addCriterion("ID <>", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThan(Integer value) {
            addCriterion("ID >", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("ID >=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThan(Integer value) {
            addCriterion("ID <", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThanOrEqualTo(Integer value) {
            addCriterion("ID <=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdIn(List<Integer> values) {
            addCriterion("ID in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotIn(List<Integer> values) {
            addCriterion("ID not in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdBetween(Integer value1, Integer value2) {
            addCriterion("ID between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotBetween(Integer value1, Integer value2) {
            addCriterion("ID not between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andAccidIsNull() {
            addCriterion("ACCID is null");
            return (Criteria) this;
        }

        public Criteria andAccidIsNotNull() {
            addCriterion("ACCID is not null");
            return (Criteria) this;
        }

        public Criteria andAccidEqualTo(Integer value) {
            addCriterion("ACCID =", value, "accid");
            return (Criteria) this;
        }

        public Criteria andAccidNotEqualTo(Integer value) {
            addCriterion("ACCID <>", value, "accid");
            return (Criteria) this;
        }

        public Criteria andAccidGreaterThan(Integer value) {
            addCriterion("ACCID >", value, "accid");
            return (Criteria) this;
        }

        public Criteria andAccidGreaterThanOrEqualTo(Integer value) {
            addCriterion("ACCID >=", value, "accid");
            return (Criteria) this;
        }

        public Criteria andAccidLessThan(Integer value) {
            addCriterion("ACCID <", value, "accid");
            return (Criteria) this;
        }

        public Criteria andAccidLessThanOrEqualTo(Integer value) {
            addCriterion("ACCID <=", value, "accid");
            return (Criteria) this;
        }

        public Criteria andAccidIn(List<Integer> values) {
            addCriterion("ACCID in", values, "accid");
            return (Criteria) this;
        }

        public Criteria andAccidNotIn(List<Integer> values) {
            addCriterion("ACCID not in", values, "accid");
            return (Criteria) this;
        }

        public Criteria andAccidBetween(Integer value1, Integer value2) {
            addCriterion("ACCID between", value1, value2, "accid");
            return (Criteria) this;
        }

        public Criteria andAccidNotBetween(Integer value1, Integer value2) {
            addCriterion("ACCID not between", value1, value2, "accid");
            return (Criteria) this;
        }

        public Criteria andUsernameIsNull() {
            addCriterion("USERNAME is null");
            return (Criteria) this;
        }

        public Criteria andUsernameIsNotNull() {
            addCriterion("USERNAME is not null");
            return (Criteria) this;
        }

        public Criteria andUsernameEqualTo(String value) {
            addCriterion("USERNAME =", value, "username");
            return (Criteria) this;
        }

        public Criteria andUsernameNotEqualTo(String value) {
            addCriterion("USERNAME <>", value, "username");
            return (Criteria) this;
        }

        public Criteria andUsernameGreaterThan(String value) {
            addCriterion("USERNAME >", value, "username");
            return (Criteria) this;
        }

        public Criteria andUsernameGreaterThanOrEqualTo(String value) {
            addCriterion("USERNAME >=", value, "username");
            return (Criteria) this;
        }

        public Criteria andUsernameLessThan(String value) {
            addCriterion("USERNAME <", value, "username");
            return (Criteria) this;
        }

        public Criteria andUsernameLessThanOrEqualTo(String value) {
            addCriterion("USERNAME <=", value, "username");
            return (Criteria) this;
        }

        public Criteria andUsernameLike(String value) {
            addCriterion("USERNAME like", value, "username");
            return (Criteria) this;
        }

        public Criteria andUsernameNotLike(String value) {
            addCriterion("USERNAME not like", value, "username");
            return (Criteria) this;
        }

        public Criteria andUsernameIn(List<String> values) {
            addCriterion("USERNAME in", values, "username");
            return (Criteria) this;
        }

        public Criteria andUsernameNotIn(List<String> values) {
            addCriterion("USERNAME not in", values, "username");
            return (Criteria) this;
        }

        public Criteria andUsernameBetween(String value1, String value2) {
            addCriterion("USERNAME between", value1, value2, "username");
            return (Criteria) this;
        }

        public Criteria andUsernameNotBetween(String value1, String value2) {
            addCriterion("USERNAME not between", value1, value2, "username");
            return (Criteria) this;
        }

        public Criteria andPasswordIsNull() {
            addCriterion("PASSWORD is null");
            return (Criteria) this;
        }

        public Criteria andPasswordIsNotNull() {
            addCriterion("PASSWORD is not null");
            return (Criteria) this;
        }

        public Criteria andPasswordEqualTo(String value) {
            addCriterion("PASSWORD =", value, "password");
            return (Criteria) this;
        }

        public Criteria andPasswordNotEqualTo(String value) {
            addCriterion("PASSWORD <>", value, "password");
            return (Criteria) this;
        }

        public Criteria andPasswordGreaterThan(String value) {
            addCriterion("PASSWORD >", value, "password");
            return (Criteria) this;
        }

        public Criteria andPasswordGreaterThanOrEqualTo(String value) {
            addCriterion("PASSWORD >=", value, "password");
            return (Criteria) this;
        }

        public Criteria andPasswordLessThan(String value) {
            addCriterion("PASSWORD <", value, "password");
            return (Criteria) this;
        }

        public Criteria andPasswordLessThanOrEqualTo(String value) {
            addCriterion("PASSWORD <=", value, "password");
            return (Criteria) this;
        }

        public Criteria andPasswordLike(String value) {
            addCriterion("PASSWORD like", value, "password");
            return (Criteria) this;
        }

        public Criteria andPasswordNotLike(String value) {
            addCriterion("PASSWORD not like", value, "password");
            return (Criteria) this;
        }

        public Criteria andPasswordIn(List<String> values) {
            addCriterion("PASSWORD in", values, "password");
            return (Criteria) this;
        }

        public Criteria andPasswordNotIn(List<String> values) {
            addCriterion("PASSWORD not in", values, "password");
            return (Criteria) this;
        }

        public Criteria andPasswordBetween(String value1, String value2) {
            addCriterion("PASSWORD between", value1, value2, "password");
            return (Criteria) this;
        }

        public Criteria andPasswordNotBetween(String value1, String value2) {
            addCriterion("PASSWORD not between", value1, value2, "password");
            return (Criteria) this;
        }

        public Criteria andCreatetimeIsNull() {
            addCriterion("CREATETIME is null");
            return (Criteria) this;
        }

        public Criteria andCreatetimeIsNotNull() {
            addCriterion("CREATETIME is not null");
            return (Criteria) this;
        }

        public Criteria andCreatetimeEqualTo(String value) {
            addCriterion("CREATETIME =", value, "createtime");
            return (Criteria) this;
        }

        public Criteria andCreatetimeNotEqualTo(String value) {
            addCriterion("CREATETIME <>", value, "createtime");
            return (Criteria) this;
        }

        public Criteria andCreatetimeGreaterThan(String value) {
            addCriterion("CREATETIME >", value, "createtime");
            return (Criteria) this;
        }

        public Criteria andCreatetimeGreaterThanOrEqualTo(String value) {
            addCriterion("CREATETIME >=", value, "createtime");
            return (Criteria) this;
        }

        public Criteria andCreatetimeLessThan(String value) {
            addCriterion("CREATETIME <", value, "createtime");
            return (Criteria) this;
        }

        public Criteria andCreatetimeLessThanOrEqualTo(String value) {
            addCriterion("CREATETIME <=", value, "createtime");
            return (Criteria) this;
        }

        public Criteria andCreatetimeLike(String value) {
            addCriterion("CREATETIME like", value, "createtime");
            return (Criteria) this;
        }

        public Criteria andCreatetimeNotLike(String value) {
            addCriterion("CREATETIME not like", value, "createtime");
            return (Criteria) this;
        }

        public Criteria andCreatetimeIn(List<String> values) {
            addCriterion("CREATETIME in", values, "createtime");
            return (Criteria) this;
        }

        public Criteria andCreatetimeNotIn(List<String> values) {
            addCriterion("CREATETIME not in", values, "createtime");
            return (Criteria) this;
        }

        public Criteria andCreatetimeBetween(String value1, String value2) {
            addCriterion("CREATETIME between", value1, value2, "createtime");
            return (Criteria) this;
        }

        public Criteria andCreatetimeNotBetween(String value1, String value2) {
            addCriterion("CREATETIME not between", value1, value2, "createtime");
            return (Criteria) this;
        }

        public Criteria andBitmaskIsNull() {
            addCriterion("BITMASK is null");
            return (Criteria) this;
        }

        public Criteria andBitmaskIsNotNull() {
            addCriterion("BITMASK is not null");
            return (Criteria) this;
        }

        public Criteria andBitmaskEqualTo(Byte value) {
            addCriterion("BITMASK =", value, "bitmask");
            return (Criteria) this;
        }

        public Criteria andBitmaskNotEqualTo(Byte value) {
            addCriterion("BITMASK <>", value, "bitmask");
            return (Criteria) this;
        }

        public Criteria andBitmaskGreaterThan(Byte value) {
            addCriterion("BITMASK >", value, "bitmask");
            return (Criteria) this;
        }

        public Criteria andBitmaskGreaterThanOrEqualTo(Byte value) {
            addCriterion("BITMASK >=", value, "bitmask");
            return (Criteria) this;
        }

        public Criteria andBitmaskLessThan(Byte value) {
            addCriterion("BITMASK <", value, "bitmask");
            return (Criteria) this;
        }

        public Criteria andBitmaskLessThanOrEqualTo(Byte value) {
            addCriterion("BITMASK <=", value, "bitmask");
            return (Criteria) this;
        }

        public Criteria andBitmaskIn(List<Byte> values) {
            addCriterion("BITMASK in", values, "bitmask");
            return (Criteria) this;
        }

        public Criteria andBitmaskNotIn(List<Byte> values) {
            addCriterion("BITMASK not in", values, "bitmask");
            return (Criteria) this;
        }

        public Criteria andBitmaskBetween(Byte value1, Byte value2) {
            addCriterion("BITMASK between", value1, value2, "bitmask");
            return (Criteria) this;
        }

        public Criteria andBitmaskNotBetween(Byte value1, Byte value2) {
            addCriterion("BITMASK not between", value1, value2, "bitmask");
            return (Criteria) this;
        }

        public Criteria andForbidtimeIsNull() {
            addCriterion("FORBIDTIME is null");
            return (Criteria) this;
        }

        public Criteria andForbidtimeIsNotNull() {
            addCriterion("FORBIDTIME is not null");
            return (Criteria) this;
        }

        public Criteria andForbidtimeEqualTo(Integer value) {
            addCriterion("FORBIDTIME =", value, "forbidtime");
            return (Criteria) this;
        }

        public Criteria andForbidtimeNotEqualTo(Integer value) {
            addCriterion("FORBIDTIME <>", value, "forbidtime");
            return (Criteria) this;
        }

        public Criteria andForbidtimeGreaterThan(Integer value) {
            addCriterion("FORBIDTIME >", value, "forbidtime");
            return (Criteria) this;
        }

        public Criteria andForbidtimeGreaterThanOrEqualTo(Integer value) {
            addCriterion("FORBIDTIME >=", value, "forbidtime");
            return (Criteria) this;
        }

        public Criteria andForbidtimeLessThan(Integer value) {
            addCriterion("FORBIDTIME <", value, "forbidtime");
            return (Criteria) this;
        }

        public Criteria andForbidtimeLessThanOrEqualTo(Integer value) {
            addCriterion("FORBIDTIME <=", value, "forbidtime");
            return (Criteria) this;
        }

        public Criteria andForbidtimeIn(List<Integer> values) {
            addCriterion("FORBIDTIME in", values, "forbidtime");
            return (Criteria) this;
        }

        public Criteria andForbidtimeNotIn(List<Integer> values) {
            addCriterion("FORBIDTIME not in", values, "forbidtime");
            return (Criteria) this;
        }

        public Criteria andForbidtimeBetween(Integer value1, Integer value2) {
            addCriterion("FORBIDTIME between", value1, value2, "forbidtime");
            return (Criteria) this;
        }

        public Criteria andForbidtimeNotBetween(Integer value1, Integer value2) {
            addCriterion("FORBIDTIME not between", value1, value2, "forbidtime");
            return (Criteria) this;
        }

        public Criteria andLastlogintimeIsNull() {
            addCriterion("LASTLOGINTIME is null");
            return (Criteria) this;
        }

        public Criteria andLastlogintimeIsNotNull() {
            addCriterion("LASTLOGINTIME is not null");
            return (Criteria) this;
        }

        public Criteria andLastlogintimeEqualTo(String value) {
            addCriterion("LASTLOGINTIME =", value, "lastlogintime");
            return (Criteria) this;
        }

        public Criteria andLastlogintimeNotEqualTo(String value) {
            addCriterion("LASTLOGINTIME <>", value, "lastlogintime");
            return (Criteria) this;
        }

        public Criteria andLastlogintimeGreaterThan(String value) {
            addCriterion("LASTLOGINTIME >", value, "lastlogintime");
            return (Criteria) this;
        }

        public Criteria andLastlogintimeGreaterThanOrEqualTo(String value) {
            addCriterion("LASTLOGINTIME >=", value, "lastlogintime");
            return (Criteria) this;
        }

        public Criteria andLastlogintimeLessThan(String value) {
            addCriterion("LASTLOGINTIME <", value, "lastlogintime");
            return (Criteria) this;
        }

        public Criteria andLastlogintimeLessThanOrEqualTo(String value) {
            addCriterion("LASTLOGINTIME <=", value, "lastlogintime");
            return (Criteria) this;
        }

        public Criteria andLastlogintimeLike(String value) {
            addCriterion("LASTLOGINTIME like", value, "lastlogintime");
            return (Criteria) this;
        }

        public Criteria andLastlogintimeNotLike(String value) {
            addCriterion("LASTLOGINTIME not like", value, "lastlogintime");
            return (Criteria) this;
        }

        public Criteria andLastlogintimeIn(List<String> values) {
            addCriterion("LASTLOGINTIME in", values, "lastlogintime");
            return (Criteria) this;
        }

        public Criteria andLastlogintimeNotIn(List<String> values) {
            addCriterion("LASTLOGINTIME not in", values, "lastlogintime");
            return (Criteria) this;
        }

        public Criteria andLastlogintimeBetween(String value1, String value2) {
            addCriterion("LASTLOGINTIME between", value1, value2, "lastlogintime");
            return (Criteria) this;
        }

        public Criteria andLastlogintimeNotBetween(String value1, String value2) {
            addCriterion("LASTLOGINTIME not between", value1, value2, "lastlogintime");
            return (Criteria) this;
        }

        public Criteria andMobileIsNull() {
            addCriterion("MOBILE is null");
            return (Criteria) this;
        }

        public Criteria andMobileIsNotNull() {
            addCriterion("MOBILE is not null");
            return (Criteria) this;
        }

        public Criteria andMobileEqualTo(String value) {
            addCriterion("MOBILE =", value, "mobile");
            return (Criteria) this;
        }

        public Criteria andMobileNotEqualTo(String value) {
            addCriterion("MOBILE <>", value, "mobile");
            return (Criteria) this;
        }

        public Criteria andMobileGreaterThan(String value) {
            addCriterion("MOBILE >", value, "mobile");
            return (Criteria) this;
        }

        public Criteria andMobileGreaterThanOrEqualTo(String value) {
            addCriterion("MOBILE >=", value, "mobile");
            return (Criteria) this;
        }

        public Criteria andMobileLessThan(String value) {
            addCriterion("MOBILE <", value, "mobile");
            return (Criteria) this;
        }

        public Criteria andMobileLessThanOrEqualTo(String value) {
            addCriterion("MOBILE <=", value, "mobile");
            return (Criteria) this;
        }

        public Criteria andMobileLike(String value) {
            addCriterion("MOBILE like", value, "mobile");
            return (Criteria) this;
        }

        public Criteria andMobileNotLike(String value) {
            addCriterion("MOBILE not like", value, "mobile");
            return (Criteria) this;
        }

        public Criteria andMobileIn(List<String> values) {
            addCriterion("MOBILE in", values, "mobile");
            return (Criteria) this;
        }

        public Criteria andMobileNotIn(List<String> values) {
            addCriterion("MOBILE not in", values, "mobile");
            return (Criteria) this;
        }

        public Criteria andMobileBetween(String value1, String value2) {
            addCriterion("MOBILE between", value1, value2, "mobile");
            return (Criteria) this;
        }

        public Criteria andMobileNotBetween(String value1, String value2) {
            addCriterion("MOBILE not between", value1, value2, "mobile");
            return (Criteria) this;
        }

        public Criteria andDevstringIsNull() {
            addCriterion("DEVSTRING is null");
            return (Criteria) this;
        }

        public Criteria andDevstringIsNotNull() {
            addCriterion("DEVSTRING is not null");
            return (Criteria) this;
        }

        public Criteria andDevstringEqualTo(String value) {
            addCriterion("DEVSTRING =", value, "devstring");
            return (Criteria) this;
        }

        public Criteria andDevstringNotEqualTo(String value) {
            addCriterion("DEVSTRING <>", value, "devstring");
            return (Criteria) this;
        }

        public Criteria andDevstringGreaterThan(String value) {
            addCriterion("DEVSTRING >", value, "devstring");
            return (Criteria) this;
        }

        public Criteria andDevstringGreaterThanOrEqualTo(String value) {
            addCriterion("DEVSTRING >=", value, "devstring");
            return (Criteria) this;
        }

        public Criteria andDevstringLessThan(String value) {
            addCriterion("DEVSTRING <", value, "devstring");
            return (Criteria) this;
        }

        public Criteria andDevstringLessThanOrEqualTo(String value) {
            addCriterion("DEVSTRING <=", value, "devstring");
            return (Criteria) this;
        }

        public Criteria andDevstringLike(String value) {
            addCriterion("DEVSTRING like", value, "devstring");
            return (Criteria) this;
        }

        public Criteria andDevstringNotLike(String value) {
            addCriterion("DEVSTRING not like", value, "devstring");
            return (Criteria) this;
        }

        public Criteria andDevstringIn(List<String> values) {
            addCriterion("DEVSTRING in", values, "devstring");
            return (Criteria) this;
        }

        public Criteria andDevstringNotIn(List<String> values) {
            addCriterion("DEVSTRING not in", values, "devstring");
            return (Criteria) this;
        }

        public Criteria andDevstringBetween(String value1, String value2) {
            addCriterion("DEVSTRING between", value1, value2, "devstring");
            return (Criteria) this;
        }

        public Criteria andDevstringNotBetween(String value1, String value2) {
            addCriterion("DEVSTRING not between", value1, value2, "devstring");
            return (Criteria) this;
        }

        public Criteria andPackageflagIsNull() {
            addCriterion("PACKAGEFLAG is null");
            return (Criteria) this;
        }

        public Criteria andPackageflagIsNotNull() {
            addCriterion("PACKAGEFLAG is not null");
            return (Criteria) this;
        }

        public Criteria andPackageflagEqualTo(String value) {
            addCriterion("PACKAGEFLAG =", value, "packageflag");
            return (Criteria) this;
        }

        public Criteria andPackageflagNotEqualTo(String value) {
            addCriterion("PACKAGEFLAG <>", value, "packageflag");
            return (Criteria) this;
        }

        public Criteria andPackageflagGreaterThan(String value) {
            addCriterion("PACKAGEFLAG >", value, "packageflag");
            return (Criteria) this;
        }

        public Criteria andPackageflagGreaterThanOrEqualTo(String value) {
            addCriterion("PACKAGEFLAG >=", value, "packageflag");
            return (Criteria) this;
        }

        public Criteria andPackageflagLessThan(String value) {
            addCriterion("PACKAGEFLAG <", value, "packageflag");
            return (Criteria) this;
        }

        public Criteria andPackageflagLessThanOrEqualTo(String value) {
            addCriterion("PACKAGEFLAG <=", value, "packageflag");
            return (Criteria) this;
        }

        public Criteria andPackageflagLike(String value) {
            addCriterion("PACKAGEFLAG like", value, "packageflag");
            return (Criteria) this;
        }

        public Criteria andPackageflagNotLike(String value) {
            addCriterion("PACKAGEFLAG not like", value, "packageflag");
            return (Criteria) this;
        }

        public Criteria andPackageflagIn(List<String> values) {
            addCriterion("PACKAGEFLAG in", values, "packageflag");
            return (Criteria) this;
        }

        public Criteria andPackageflagNotIn(List<String> values) {
            addCriterion("PACKAGEFLAG not in", values, "packageflag");
            return (Criteria) this;
        }

        public Criteria andPackageflagBetween(String value1, String value2) {
            addCriterion("PACKAGEFLAG between", value1, value2, "packageflag");
            return (Criteria) this;
        }

        public Criteria andPackageflagNotBetween(String value1, String value2) {
            addCriterion("PACKAGEFLAG not between", value1, value2, "packageflag");
            return (Criteria) this;
        }

        public Criteria andLoginpackagetypeIsNull() {
            addCriterion("LOGINPACKAGETYPE is null");
            return (Criteria) this;
        }

        public Criteria andLoginpackagetypeIsNotNull() {
            addCriterion("LOGINPACKAGETYPE is not null");
            return (Criteria) this;
        }

        public Criteria andLoginpackagetypeEqualTo(Integer value) {
            addCriterion("LOGINPACKAGETYPE =", value, "loginpackagetype");
            return (Criteria) this;
        }

        public Criteria andLoginpackagetypeNotEqualTo(Integer value) {
            addCriterion("LOGINPACKAGETYPE <>", value, "loginpackagetype");
            return (Criteria) this;
        }

        public Criteria andLoginpackagetypeGreaterThan(Integer value) {
            addCriterion("LOGINPACKAGETYPE >", value, "loginpackagetype");
            return (Criteria) this;
        }

        public Criteria andLoginpackagetypeGreaterThanOrEqualTo(Integer value) {
            addCriterion("LOGINPACKAGETYPE >=", value, "loginpackagetype");
            return (Criteria) this;
        }

        public Criteria andLoginpackagetypeLessThan(Integer value) {
            addCriterion("LOGINPACKAGETYPE <", value, "loginpackagetype");
            return (Criteria) this;
        }

        public Criteria andLoginpackagetypeLessThanOrEqualTo(Integer value) {
            addCriterion("LOGINPACKAGETYPE <=", value, "loginpackagetype");
            return (Criteria) this;
        }

        public Criteria andLoginpackagetypeIn(List<Integer> values) {
            addCriterion("LOGINPACKAGETYPE in", values, "loginpackagetype");
            return (Criteria) this;
        }

        public Criteria andLoginpackagetypeNotIn(List<Integer> values) {
            addCriterion("LOGINPACKAGETYPE not in", values, "loginpackagetype");
            return (Criteria) this;
        }

        public Criteria andLoginpackagetypeBetween(Integer value1, Integer value2) {
            addCriterion("LOGINPACKAGETYPE between", value1, value2, "loginpackagetype");
            return (Criteria) this;
        }

        public Criteria andLoginpackagetypeNotBetween(Integer value1, Integer value2) {
            addCriterion("LOGINPACKAGETYPE not between", value1, value2, "loginpackagetype");
            return (Criteria) this;
        }

        public Criteria andPackagetypeIsNull() {
            addCriterion("PACKAGETYPE is null");
            return (Criteria) this;
        }

        public Criteria andPackagetypeIsNotNull() {
            addCriterion("PACKAGETYPE is not null");
            return (Criteria) this;
        }

        public Criteria andPackagetypeEqualTo(Integer value) {
            addCriterion("PACKAGETYPE =", value, "packagetype");
            return (Criteria) this;
        }

        public Criteria andPackagetypeNotEqualTo(Integer value) {
            addCriterion("PACKAGETYPE <>", value, "packagetype");
            return (Criteria) this;
        }

        public Criteria andPackagetypeGreaterThan(Integer value) {
            addCriterion("PACKAGETYPE >", value, "packagetype");
            return (Criteria) this;
        }

        public Criteria andPackagetypeGreaterThanOrEqualTo(Integer value) {
            addCriterion("PACKAGETYPE >=", value, "packagetype");
            return (Criteria) this;
        }

        public Criteria andPackagetypeLessThan(Integer value) {
            addCriterion("PACKAGETYPE <", value, "packagetype");
            return (Criteria) this;
        }

        public Criteria andPackagetypeLessThanOrEqualTo(Integer value) {
            addCriterion("PACKAGETYPE <=", value, "packagetype");
            return (Criteria) this;
        }

        public Criteria andPackagetypeIn(List<Integer> values) {
            addCriterion("PACKAGETYPE in", values, "packagetype");
            return (Criteria) this;
        }

        public Criteria andPackagetypeNotIn(List<Integer> values) {
            addCriterion("PACKAGETYPE not in", values, "packagetype");
            return (Criteria) this;
        }

        public Criteria andPackagetypeBetween(Integer value1, Integer value2) {
            addCriterion("PACKAGETYPE between", value1, value2, "packagetype");
            return (Criteria) this;
        }

        public Criteria andPackagetypeNotBetween(Integer value1, Integer value2) {
            addCriterion("PACKAGETYPE not between", value1, value2, "packagetype");
            return (Criteria) this;
        }

        public Criteria andCounttypeIsNull() {
            addCriterion("COUNTTYPE is null");
            return (Criteria) this;
        }

        public Criteria andCounttypeIsNotNull() {
            addCriterion("COUNTTYPE is not null");
            return (Criteria) this;
        }

        public Criteria andCounttypeEqualTo(Integer value) {
            addCriterion("COUNTTYPE =", value, "counttype");
            return (Criteria) this;
        }

        public Criteria andCounttypeNotEqualTo(Integer value) {
            addCriterion("COUNTTYPE <>", value, "counttype");
            return (Criteria) this;
        }

        public Criteria andCounttypeGreaterThan(Integer value) {
            addCriterion("COUNTTYPE >", value, "counttype");
            return (Criteria) this;
        }

        public Criteria andCounttypeGreaterThanOrEqualTo(Integer value) {
            addCriterion("COUNTTYPE >=", value, "counttype");
            return (Criteria) this;
        }

        public Criteria andCounttypeLessThan(Integer value) {
            addCriterion("COUNTTYPE <", value, "counttype");
            return (Criteria) this;
        }

        public Criteria andCounttypeLessThanOrEqualTo(Integer value) {
            addCriterion("COUNTTYPE <=", value, "counttype");
            return (Criteria) this;
        }

        public Criteria andCounttypeIn(List<Integer> values) {
            addCriterion("COUNTTYPE in", values, "counttype");
            return (Criteria) this;
        }

        public Criteria andCounttypeNotIn(List<Integer> values) {
            addCriterion("COUNTTYPE not in", values, "counttype");
            return (Criteria) this;
        }

        public Criteria andCounttypeBetween(Integer value1, Integer value2) {
            addCriterion("COUNTTYPE between", value1, value2, "counttype");
            return (Criteria) this;
        }

        public Criteria andCounttypeNotBetween(Integer value1, Integer value2) {
            addCriterion("COUNTTYPE not between", value1, value2, "counttype");
            return (Criteria) this;
        }

        public Criteria andRegiestipIsNull() {
            addCriterion("REGIESTIP is null");
            return (Criteria) this;
        }

        public Criteria andRegiestipIsNotNull() {
            addCriterion("REGIESTIP is not null");
            return (Criteria) this;
        }

        public Criteria andRegiestipEqualTo(String value) {
            addCriterion("REGIESTIP =", value, "regiestip");
            return (Criteria) this;
        }

        public Criteria andRegiestipNotEqualTo(String value) {
            addCriterion("REGIESTIP <>", value, "regiestip");
            return (Criteria) this;
        }

        public Criteria andRegiestipGreaterThan(String value) {
            addCriterion("REGIESTIP >", value, "regiestip");
            return (Criteria) this;
        }

        public Criteria andRegiestipGreaterThanOrEqualTo(String value) {
            addCriterion("REGIESTIP >=", value, "regiestip");
            return (Criteria) this;
        }

        public Criteria andRegiestipLessThan(String value) {
            addCriterion("REGIESTIP <", value, "regiestip");
            return (Criteria) this;
        }

        public Criteria andRegiestipLessThanOrEqualTo(String value) {
            addCriterion("REGIESTIP <=", value, "regiestip");
            return (Criteria) this;
        }

        public Criteria andRegiestipLike(String value) {
            addCriterion("REGIESTIP like", value, "regiestip");
            return (Criteria) this;
        }

        public Criteria andRegiestipNotLike(String value) {
            addCriterion("REGIESTIP not like", value, "regiestip");
            return (Criteria) this;
        }

        public Criteria andRegiestipIn(List<String> values) {
            addCriterion("REGIESTIP in", values, "regiestip");
            return (Criteria) this;
        }

        public Criteria andRegiestipNotIn(List<String> values) {
            addCriterion("REGIESTIP not in", values, "regiestip");
            return (Criteria) this;
        }

        public Criteria andRegiestipBetween(String value1, String value2) {
            addCriterion("REGIESTIP between", value1, value2, "regiestip");
            return (Criteria) this;
        }

        public Criteria andRegiestipNotBetween(String value1, String value2) {
            addCriterion("REGIESTIP not between", value1, value2, "regiestip");
            return (Criteria) this;
        }

        public Criteria andLogindevstringIsNull() {
            addCriterion("LOGINDEVSTRING is null");
            return (Criteria) this;
        }

        public Criteria andLogindevstringIsNotNull() {
            addCriterion("LOGINDEVSTRING is not null");
            return (Criteria) this;
        }

        public Criteria andLogindevstringEqualTo(String value) {
            addCriterion("LOGINDEVSTRING =", value, "logindevstring");
            return (Criteria) this;
        }

        public Criteria andLogindevstringNotEqualTo(String value) {
            addCriterion("LOGINDEVSTRING <>", value, "logindevstring");
            return (Criteria) this;
        }

        public Criteria andLogindevstringGreaterThan(String value) {
            addCriterion("LOGINDEVSTRING >", value, "logindevstring");
            return (Criteria) this;
        }

        public Criteria andLogindevstringGreaterThanOrEqualTo(String value) {
            addCriterion("LOGINDEVSTRING >=", value, "logindevstring");
            return (Criteria) this;
        }

        public Criteria andLogindevstringLessThan(String value) {
            addCriterion("LOGINDEVSTRING <", value, "logindevstring");
            return (Criteria) this;
        }

        public Criteria andLogindevstringLessThanOrEqualTo(String value) {
            addCriterion("LOGINDEVSTRING <=", value, "logindevstring");
            return (Criteria) this;
        }

        public Criteria andLogindevstringLike(String value) {
            addCriterion("LOGINDEVSTRING like", value, "logindevstring");
            return (Criteria) this;
        }

        public Criteria andLogindevstringNotLike(String value) {
            addCriterion("LOGINDEVSTRING not like", value, "logindevstring");
            return (Criteria) this;
        }

        public Criteria andLogindevstringIn(List<String> values) {
            addCriterion("LOGINDEVSTRING in", values, "logindevstring");
            return (Criteria) this;
        }

        public Criteria andLogindevstringNotIn(List<String> values) {
            addCriterion("LOGINDEVSTRING not in", values, "logindevstring");
            return (Criteria) this;
        }

        public Criteria andLogindevstringBetween(String value1, String value2) {
            addCriterion("LOGINDEVSTRING between", value1, value2, "logindevstring");
            return (Criteria) this;
        }

        public Criteria andLogindevstringNotBetween(String value1, String value2) {
            addCriterion("LOGINDEVSTRING not between", value1, value2, "logindevstring");
            return (Criteria) this;
        }

        public Criteria andLoginpackageflagIsNull() {
            addCriterion("LOGINPACKAGEFLAG is null");
            return (Criteria) this;
        }

        public Criteria andLoginpackageflagIsNotNull() {
            addCriterion("LOGINPACKAGEFLAG is not null");
            return (Criteria) this;
        }

        public Criteria andLoginpackageflagEqualTo(String value) {
            addCriterion("LOGINPACKAGEFLAG =", value, "loginpackageflag");
            return (Criteria) this;
        }

        public Criteria andLoginpackageflagNotEqualTo(String value) {
            addCriterion("LOGINPACKAGEFLAG <>", value, "loginpackageflag");
            return (Criteria) this;
        }

        public Criteria andLoginpackageflagGreaterThan(String value) {
            addCriterion("LOGINPACKAGEFLAG >", value, "loginpackageflag");
            return (Criteria) this;
        }

        public Criteria andLoginpackageflagGreaterThanOrEqualTo(String value) {
            addCriterion("LOGINPACKAGEFLAG >=", value, "loginpackageflag");
            return (Criteria) this;
        }

        public Criteria andLoginpackageflagLessThan(String value) {
            addCriterion("LOGINPACKAGEFLAG <", value, "loginpackageflag");
            return (Criteria) this;
        }

        public Criteria andLoginpackageflagLessThanOrEqualTo(String value) {
            addCriterion("LOGINPACKAGEFLAG <=", value, "loginpackageflag");
            return (Criteria) this;
        }

        public Criteria andLoginpackageflagLike(String value) {
            addCriterion("LOGINPACKAGEFLAG like", value, "loginpackageflag");
            return (Criteria) this;
        }

        public Criteria andLoginpackageflagNotLike(String value) {
            addCriterion("LOGINPACKAGEFLAG not like", value, "loginpackageflag");
            return (Criteria) this;
        }

        public Criteria andLoginpackageflagIn(List<String> values) {
            addCriterion("LOGINPACKAGEFLAG in", values, "loginpackageflag");
            return (Criteria) this;
        }

        public Criteria andLoginpackageflagNotIn(List<String> values) {
            addCriterion("LOGINPACKAGEFLAG not in", values, "loginpackageflag");
            return (Criteria) this;
        }

        public Criteria andLoginpackageflagBetween(String value1, String value2) {
            addCriterion("LOGINPACKAGEFLAG between", value1, value2, "loginpackageflag");
            return (Criteria) this;
        }

        public Criteria andLoginpackageflagNotBetween(String value1, String value2) {
            addCriterion("LOGINPACKAGEFLAG not between", value1, value2, "loginpackageflag");
            return (Criteria) this;
        }

        public Criteria andSpreadidIsNull() {
            addCriterion("SPREADID is null");
            return (Criteria) this;
        }

        public Criteria andSpreadidIsNotNull() {
            addCriterion("SPREADID is not null");
            return (Criteria) this;
        }

        public Criteria andSpreadidEqualTo(Integer value) {
            addCriterion("SPREADID =", value, "spreadid");
            return (Criteria) this;
        }

        public Criteria andSpreadidNotEqualTo(Integer value) {
            addCriterion("SPREADID <>", value, "spreadid");
            return (Criteria) this;
        }

        public Criteria andSpreadidGreaterThan(Integer value) {
            addCriterion("SPREADID >", value, "spreadid");
            return (Criteria) this;
        }

        public Criteria andSpreadidGreaterThanOrEqualTo(Integer value) {
            addCriterion("SPREADID >=", value, "spreadid");
            return (Criteria) this;
        }

        public Criteria andSpreadidLessThan(Integer value) {
            addCriterion("SPREADID <", value, "spreadid");
            return (Criteria) this;
        }

        public Criteria andSpreadidLessThanOrEqualTo(Integer value) {
            addCriterion("SPREADID <=", value, "spreadid");
            return (Criteria) this;
        }

        public Criteria andSpreadidIn(List<Integer> values) {
            addCriterion("SPREADID in", values, "spreadid");
            return (Criteria) this;
        }

        public Criteria andSpreadidNotIn(List<Integer> values) {
            addCriterion("SPREADID not in", values, "spreadid");
            return (Criteria) this;
        }

        public Criteria andSpreadidBetween(Integer value1, Integer value2) {
            addCriterion("SPREADID between", value1, value2, "spreadid");
            return (Criteria) this;
        }

        public Criteria andSpreadidNotBetween(Integer value1, Integer value2) {
            addCriterion("SPREADID not between", value1, value2, "spreadid");
            return (Criteria) this;
        }

        public Criteria andRegisttimeIsNull() {
            addCriterion("RegistTime is null");
            return (Criteria) this;
        }

        public Criteria andRegisttimeIsNotNull() {
            addCriterion("RegistTime is not null");
            return (Criteria) this;
        }

        public Criteria andRegisttimeEqualTo(Long value) {
            addCriterion("RegistTime =", value, "registtime");
            return (Criteria) this;
        }

        public Criteria andRegisttimeNotEqualTo(Long value) {
            addCriterion("RegistTime <>", value, "registtime");
            return (Criteria) this;
        }

        public Criteria andRegisttimeGreaterThan(Long value) {
            addCriterion("RegistTime >", value, "registtime");
            return (Criteria) this;
        }

        public Criteria andRegisttimeGreaterThanOrEqualTo(Long value) {
            addCriterion("RegistTime >=", value, "registtime");
            return (Criteria) this;
        }

        public Criteria andRegisttimeLessThan(Long value) {
            addCriterion("RegistTime <", value, "registtime");
            return (Criteria) this;
        }

        public Criteria andRegisttimeLessThanOrEqualTo(Long value) {
            addCriterion("RegistTime <=", value, "registtime");
            return (Criteria) this;
        }

        public Criteria andRegisttimeIn(List<Long> values) {
            addCriterion("RegistTime in", values, "registtime");
            return (Criteria) this;
        }

        public Criteria andRegisttimeNotIn(List<Long> values) {
            addCriterion("RegistTime not in", values, "registtime");
            return (Criteria) this;
        }

        public Criteria andRegisttimeBetween(Long value1, Long value2) {
            addCriterion("RegistTime between", value1, value2, "registtime");
            return (Criteria) this;
        }

        public Criteria andRegisttimeNotBetween(Long value1, Long value2) {
            addCriterion("RegistTime not between", value1, value2, "registtime");
            return (Criteria) this;
        }

        public Criteria andDevicetypeIsNull() {
            addCriterion("DEVICETYPE is null");
            return (Criteria) this;
        }

        public Criteria andDevicetypeIsNotNull() {
            addCriterion("DEVICETYPE is not null");
            return (Criteria) this;
        }

        public Criteria andDevicetypeEqualTo(Integer value) {
            addCriterion("DEVICETYPE =", value, "devicetype");
            return (Criteria) this;
        }

        public Criteria andDevicetypeNotEqualTo(Integer value) {
            addCriterion("DEVICETYPE <>", value, "devicetype");
            return (Criteria) this;
        }

        public Criteria andDevicetypeGreaterThan(Integer value) {
            addCriterion("DEVICETYPE >", value, "devicetype");
            return (Criteria) this;
        }

        public Criteria andDevicetypeGreaterThanOrEqualTo(Integer value) {
            addCriterion("DEVICETYPE >=", value, "devicetype");
            return (Criteria) this;
        }

        public Criteria andDevicetypeLessThan(Integer value) {
            addCriterion("DEVICETYPE <", value, "devicetype");
            return (Criteria) this;
        }

        public Criteria andDevicetypeLessThanOrEqualTo(Integer value) {
            addCriterion("DEVICETYPE <=", value, "devicetype");
            return (Criteria) this;
        }

        public Criteria andDevicetypeIn(List<Integer> values) {
            addCriterion("DEVICETYPE in", values, "devicetype");
            return (Criteria) this;
        }

        public Criteria andDevicetypeNotIn(List<Integer> values) {
            addCriterion("DEVICETYPE not in", values, "devicetype");
            return (Criteria) this;
        }

        public Criteria andDevicetypeBetween(Integer value1, Integer value2) {
            addCriterion("DEVICETYPE between", value1, value2, "devicetype");
            return (Criteria) this;
        }

        public Criteria andDevicetypeNotBetween(Integer value1, Integer value2) {
            addCriterion("DEVICETYPE not between", value1, value2, "devicetype");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table ACCOUNT
     *
     * @mbg.generated do_not_delete_during_merge
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table ACCOUNT
     *
     * @mbg.generated
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}