package com.leo.domain;

public class Account {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ACCOUNT.ID
     *
     * @mbg.generated
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ACCOUNT.ACCID
     *
     * @mbg.generated
     */
    private Integer accid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ACCOUNT.USERNAME
     *
     * @mbg.generated
     */
    private String username;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ACCOUNT.PASSWORD
     *
     * @mbg.generated
     */
    private String password;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ACCOUNT.CREATETIME
     *
     * @mbg.generated
     */
    private String createtime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ACCOUNT.BITMASK
     *
     * @mbg.generated
     */
    private Byte bitmask;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ACCOUNT.FORBIDTIME
     *
     * @mbg.generated
     */
    private Integer forbidtime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ACCOUNT.LASTLOGINTIME
     *
     * @mbg.generated
     */
    private String lastlogintime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ACCOUNT.MOBILE
     *
     * @mbg.generated
     */
    private String mobile;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ACCOUNT.DEVSTRING
     *
     * @mbg.generated
     */
    private String devstring;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ACCOUNT.PACKAGEFLAG
     *
     * @mbg.generated
     */
    private String packageflag;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ACCOUNT.LOGINPACKAGETYPE
     *
     * @mbg.generated
     */
    private Integer loginpackagetype;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ACCOUNT.PACKAGETYPE
     *
     * @mbg.generated
     */
    private Integer packagetype;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ACCOUNT.COUNTTYPE
     *
     * @mbg.generated
     */
    private Integer counttype;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ACCOUNT.REGIESTIP
     *
     * @mbg.generated
     */
    private String regiestip;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ACCOUNT.LOGINDEVSTRING
     *
     * @mbg.generated
     */
    private String logindevstring;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ACCOUNT.LOGINPACKAGEFLAG
     *
     * @mbg.generated
     */
    private String loginpackageflag;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ACCOUNT.SPREADID
     *
     * @mbg.generated
     */
    private Integer spreadid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ACCOUNT.RegistTime
     *
     * @mbg.generated
     */
    private Long registtime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ACCOUNT.DEVICETYPE
     *
     * @mbg.generated
     */
    private Integer devicetype;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ACCOUNT.ID
     *
     * @return the value of ACCOUNT.ID
     *
     * @mbg.generated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ACCOUNT.ID
     *
     * @param id the value for ACCOUNT.ID
     *
     * @mbg.generated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ACCOUNT.ACCID
     *
     * @return the value of ACCOUNT.ACCID
     *
     * @mbg.generated
     */
    public Integer getAccid() {
        return accid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ACCOUNT.ACCID
     *
     * @param accid the value for ACCOUNT.ACCID
     *
     * @mbg.generated
     */
    public void setAccid(Integer accid) {
        this.accid = accid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ACCOUNT.USERNAME
     *
     * @return the value of ACCOUNT.USERNAME
     *
     * @mbg.generated
     */
    public String getUsername() {
        return username;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ACCOUNT.USERNAME
     *
     * @param username the value for ACCOUNT.USERNAME
     *
     * @mbg.generated
     */
    public void setUsername(String username) {
        this.username = username == null ? null : username.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ACCOUNT.PASSWORD
     *
     * @return the value of ACCOUNT.PASSWORD
     *
     * @mbg.generated
     */
    public String getPassword() {
        return password;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ACCOUNT.PASSWORD
     *
     * @param password the value for ACCOUNT.PASSWORD
     *
     * @mbg.generated
     */
    public void setPassword(String password) {
        this.password = password == null ? null : password.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ACCOUNT.CREATETIME
     *
     * @return the value of ACCOUNT.CREATETIME
     *
     * @mbg.generated
     */
    public String getCreatetime() {
        return createtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ACCOUNT.CREATETIME
     *
     * @param createtime the value for ACCOUNT.CREATETIME
     *
     * @mbg.generated
     */
    public void setCreatetime(String createtime) {
        this.createtime = createtime == null ? null : createtime.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ACCOUNT.BITMASK
     *
     * @return the value of ACCOUNT.BITMASK
     *
     * @mbg.generated
     */
    public Byte getBitmask() {
        return bitmask;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ACCOUNT.BITMASK
     *
     * @param bitmask the value for ACCOUNT.BITMASK
     *
     * @mbg.generated
     */
    public void setBitmask(Byte bitmask) {
        this.bitmask = bitmask;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ACCOUNT.FORBIDTIME
     *
     * @return the value of ACCOUNT.FORBIDTIME
     *
     * @mbg.generated
     */
    public Integer getForbidtime() {
        return forbidtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ACCOUNT.FORBIDTIME
     *
     * @param forbidtime the value for ACCOUNT.FORBIDTIME
     *
     * @mbg.generated
     */
    public void setForbidtime(Integer forbidtime) {
        this.forbidtime = forbidtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ACCOUNT.LASTLOGINTIME
     *
     * @return the value of ACCOUNT.LASTLOGINTIME
     *
     * @mbg.generated
     */
    public String getLastlogintime() {
        return lastlogintime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ACCOUNT.LASTLOGINTIME
     *
     * @param lastlogintime the value for ACCOUNT.LASTLOGINTIME
     *
     * @mbg.generated
     */
    public void setLastlogintime(String lastlogintime) {
        this.lastlogintime = lastlogintime == null ? null : lastlogintime.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ACCOUNT.MOBILE
     *
     * @return the value of ACCOUNT.MOBILE
     *
     * @mbg.generated
     */
    public String getMobile() {
        return mobile;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ACCOUNT.MOBILE
     *
     * @param mobile the value for ACCOUNT.MOBILE
     *
     * @mbg.generated
     */
    public void setMobile(String mobile) {
        this.mobile = mobile == null ? null : mobile.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ACCOUNT.DEVSTRING
     *
     * @return the value of ACCOUNT.DEVSTRING
     *
     * @mbg.generated
     */
    public String getDevstring() {
        return devstring;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ACCOUNT.DEVSTRING
     *
     * @param devstring the value for ACCOUNT.DEVSTRING
     *
     * @mbg.generated
     */
    public void setDevstring(String devstring) {
        this.devstring = devstring == null ? null : devstring.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ACCOUNT.PACKAGEFLAG
     *
     * @return the value of ACCOUNT.PACKAGEFLAG
     *
     * @mbg.generated
     */
    public String getPackageflag() {
        return packageflag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ACCOUNT.PACKAGEFLAG
     *
     * @param packageflag the value for ACCOUNT.PACKAGEFLAG
     *
     * @mbg.generated
     */
    public void setPackageflag(String packageflag) {
        this.packageflag = packageflag == null ? null : packageflag.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ACCOUNT.LOGINPACKAGETYPE
     *
     * @return the value of ACCOUNT.LOGINPACKAGETYPE
     *
     * @mbg.generated
     */
    public Integer getLoginpackagetype() {
        return loginpackagetype;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ACCOUNT.LOGINPACKAGETYPE
     *
     * @param loginpackagetype the value for ACCOUNT.LOGINPACKAGETYPE
     *
     * @mbg.generated
     */
    public void setLoginpackagetype(Integer loginpackagetype) {
        this.loginpackagetype = loginpackagetype;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ACCOUNT.PACKAGETYPE
     *
     * @return the value of ACCOUNT.PACKAGETYPE
     *
     * @mbg.generated
     */
    public Integer getPackagetype() {
        return packagetype;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ACCOUNT.PACKAGETYPE
     *
     * @param packagetype the value for ACCOUNT.PACKAGETYPE
     *
     * @mbg.generated
     */
    public void setPackagetype(Integer packagetype) {
        this.packagetype = packagetype;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ACCOUNT.COUNTTYPE
     *
     * @return the value of ACCOUNT.COUNTTYPE
     *
     * @mbg.generated
     */
    public Integer getCounttype() {
        return counttype;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ACCOUNT.COUNTTYPE
     *
     * @param counttype the value for ACCOUNT.COUNTTYPE
     *
     * @mbg.generated
     */
    public void setCounttype(Integer counttype) {
        this.counttype = counttype;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ACCOUNT.REGIESTIP
     *
     * @return the value of ACCOUNT.REGIESTIP
     *
     * @mbg.generated
     */
    public String getRegiestip() {
        return regiestip;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ACCOUNT.REGIESTIP
     *
     * @param regiestip the value for ACCOUNT.REGIESTIP
     *
     * @mbg.generated
     */
    public void setRegiestip(String regiestip) {
        this.regiestip = regiestip == null ? null : regiestip.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ACCOUNT.LOGINDEVSTRING
     *
     * @return the value of ACCOUNT.LOGINDEVSTRING
     *
     * @mbg.generated
     */
    public String getLogindevstring() {
        return logindevstring;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ACCOUNT.LOGINDEVSTRING
     *
     * @param logindevstring the value for ACCOUNT.LOGINDEVSTRING
     *
     * @mbg.generated
     */
    public void setLogindevstring(String logindevstring) {
        this.logindevstring = logindevstring == null ? null : logindevstring.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ACCOUNT.LOGINPACKAGEFLAG
     *
     * @return the value of ACCOUNT.LOGINPACKAGEFLAG
     *
     * @mbg.generated
     */
    public String getLoginpackageflag() {
        return loginpackageflag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ACCOUNT.LOGINPACKAGEFLAG
     *
     * @param loginpackageflag the value for ACCOUNT.LOGINPACKAGEFLAG
     *
     * @mbg.generated
     */
    public void setLoginpackageflag(String loginpackageflag) {
        this.loginpackageflag = loginpackageflag == null ? null : loginpackageflag.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ACCOUNT.SPREADID
     *
     * @return the value of ACCOUNT.SPREADID
     *
     * @mbg.generated
     */
    public Integer getSpreadid() {
        return spreadid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ACCOUNT.SPREADID
     *
     * @param spreadid the value for ACCOUNT.SPREADID
     *
     * @mbg.generated
     */
    public void setSpreadid(Integer spreadid) {
        this.spreadid = spreadid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ACCOUNT.RegistTime
     *
     * @return the value of ACCOUNT.RegistTime
     *
     * @mbg.generated
     */
    public Long getRegisttime() {
        return registtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ACCOUNT.RegistTime
     *
     * @param registtime the value for ACCOUNT.RegistTime
     *
     * @mbg.generated
     */
    public void setRegisttime(Long registtime) {
        this.registtime = registtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ACCOUNT.DEVICETYPE
     *
     * @return the value of ACCOUNT.DEVICETYPE
     *
     * @mbg.generated
     */
    public Integer getDevicetype() {
        return devicetype;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ACCOUNT.DEVICETYPE
     *
     * @param devicetype the value for ACCOUNT.DEVICETYPE
     *
     * @mbg.generated
     */
    public void setDevicetype(Integer devicetype) {
        this.devicetype = devicetype;
    }
}