package com.leo.domain;

import java.io.Serializable;

public class Account implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ACCOUNT.ID
     *
     * @mbg.generated Wed Apr 29 10:35:51 CST 2020
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ACCOUNT.ACCID
     *
     * @mbg.generated Wed Apr 29 10:35:51 CST 2020
     */
    private Integer accid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ACCOUNT.USERNAME
     *
     * @mbg.generated Wed Apr 29 10:35:51 CST 2020
     */
    private String username;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ACCOUNT.PASSWORD
     *
     * @mbg.generated Wed Apr 29 10:35:51 CST 2020
     */
    private String password;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ACCOUNT.CREATETIME
     *
     * @mbg.generated Wed Apr 29 10:35:51 CST 2020
     */
    private String createtime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ACCOUNT.BITMASK
     *
     * @mbg.generated Wed Apr 29 10:35:51 CST 2020
     */
    private Byte bitmask;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ACCOUNT.FORBIDTIME
     *
     * @mbg.generated Wed Apr 29 10:35:51 CST 2020
     */
    private Integer forbidtime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ACCOUNT.LASTLOGINTIME
     *
     * @mbg.generated Wed Apr 29 10:35:51 CST 2020
     */
    private String lastlogintime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ACCOUNT.MOBILE
     *
     * @mbg.generated Wed Apr 29 10:35:51 CST 2020
     */
    private String mobile;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ACCOUNT.DEVSTRING
     *
     * @mbg.generated Wed Apr 29 10:35:51 CST 2020
     */
    private String devstring;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ACCOUNT.PACKAGEFLAG
     *
     * @mbg.generated Wed Apr 29 10:35:51 CST 2020
     */
    private String packageflag;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ACCOUNT.LOGINPACKAGETYPE
     *
     * @mbg.generated Wed Apr 29 10:35:51 CST 2020
     */
    private Integer loginpackagetype;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ACCOUNT.PACKAGETYPE
     *
     * @mbg.generated Wed Apr 29 10:35:51 CST 2020
     */
    private Integer packagetype;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ACCOUNT.COUNTTYPE
     *
     * @mbg.generated Wed Apr 29 10:35:51 CST 2020
     */
    private Integer counttype;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ACCOUNT.REGIESTIP
     *
     * @mbg.generated Wed Apr 29 10:35:51 CST 2020
     */
    private String regiestip;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ACCOUNT.LOGINDEVSTRING
     *
     * @mbg.generated Wed Apr 29 10:35:51 CST 2020
     */
    private String logindevstring;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ACCOUNT.LOGINPACKAGEFLAG
     *
     * @mbg.generated Wed Apr 29 10:35:51 CST 2020
     */
    private String loginpackageflag;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ACCOUNT.SPREADID
     *
     * @mbg.generated Wed Apr 29 10:35:51 CST 2020
     */
    private Integer spreadid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ACCOUNT.RegistTime
     *
     * @mbg.generated Wed Apr 29 10:35:51 CST 2020
     */
    private Long registtime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ACCOUNT.DEVICETYPE
     *
     * @mbg.generated Wed Apr 29 10:35:51 CST 2020
     */
    private Integer devicetype;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ACCOUNT.roletime
     *
     * @mbg.generated Wed Apr 29 10:35:51 CST 2020
     */
    private Long roletime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ACCOUNT.logindevinfo
     *
     * @mbg.generated Wed Apr 29 10:35:51 CST 2020
     */
    private String logindevinfo;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ACCOUNT.pversion
     *
     * @mbg.generated Wed Apr 29 10:35:51 CST 2020
     */
    private String pversion;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ACCOUNT.regversion
     *
     * @mbg.generated Wed Apr 29 10:35:51 CST 2020
     */
    private String regversion;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table ACCOUNT
     *
     * @mbg.generated Wed Apr 29 10:35:51 CST 2020
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ACCOUNT.ID
     *
     * @return the value of ACCOUNT.ID
     *
     * @mbg.generated Wed Apr 29 10:35:51 CST 2020
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ACCOUNT
     *
     * @mbg.generated Wed Apr 29 10:35:51 CST 2020
     */
    public Account withId(Integer id) {
        this.setId(id);
        return this;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ACCOUNT.ID
     *
     * @param id the value for ACCOUNT.ID
     *
     * @mbg.generated Wed Apr 29 10:35:51 CST 2020
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ACCOUNT.ACCID
     *
     * @return the value of ACCOUNT.ACCID
     *
     * @mbg.generated Wed Apr 29 10:35:51 CST 2020
     */
    public Integer getAccid() {
        return accid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ACCOUNT
     *
     * @mbg.generated Wed Apr 29 10:35:51 CST 2020
     */
    public Account withAccid(Integer accid) {
        this.setAccid(accid);
        return this;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ACCOUNT.ACCID
     *
     * @param accid the value for ACCOUNT.ACCID
     *
     * @mbg.generated Wed Apr 29 10:35:51 CST 2020
     */
    public void setAccid(Integer accid) {
        this.accid = accid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ACCOUNT.USERNAME
     *
     * @return the value of ACCOUNT.USERNAME
     *
     * @mbg.generated Wed Apr 29 10:35:51 CST 2020
     */
    public String getUsername() {
        return username;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ACCOUNT
     *
     * @mbg.generated Wed Apr 29 10:35:51 CST 2020
     */
    public Account withUsername(String username) {
        this.setUsername(username);
        return this;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ACCOUNT.USERNAME
     *
     * @param username the value for ACCOUNT.USERNAME
     *
     * @mbg.generated Wed Apr 29 10:35:51 CST 2020
     */
    public void setUsername(String username) {
        this.username = username == null ? null : username.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ACCOUNT.PASSWORD
     *
     * @return the value of ACCOUNT.PASSWORD
     *
     * @mbg.generated Wed Apr 29 10:35:51 CST 2020
     */
    public String getPassword() {
        return password;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ACCOUNT
     *
     * @mbg.generated Wed Apr 29 10:35:51 CST 2020
     */
    public Account withPassword(String password) {
        this.setPassword(password);
        return this;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ACCOUNT.PASSWORD
     *
     * @param password the value for ACCOUNT.PASSWORD
     *
     * @mbg.generated Wed Apr 29 10:35:51 CST 2020
     */
    public void setPassword(String password) {
        this.password = password == null ? null : password.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ACCOUNT.CREATETIME
     *
     * @return the value of ACCOUNT.CREATETIME
     *
     * @mbg.generated Wed Apr 29 10:35:51 CST 2020
     */
    public String getCreatetime() {
        return createtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ACCOUNT
     *
     * @mbg.generated Wed Apr 29 10:35:51 CST 2020
     */
    public Account withCreatetime(String createtime) {
        this.setCreatetime(createtime);
        return this;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ACCOUNT.CREATETIME
     *
     * @param createtime the value for ACCOUNT.CREATETIME
     *
     * @mbg.generated Wed Apr 29 10:35:51 CST 2020
     */
    public void setCreatetime(String createtime) {
        this.createtime = createtime == null ? null : createtime.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ACCOUNT.BITMASK
     *
     * @return the value of ACCOUNT.BITMASK
     *
     * @mbg.generated Wed Apr 29 10:35:51 CST 2020
     */
    public Byte getBitmask() {
        return bitmask;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ACCOUNT
     *
     * @mbg.generated Wed Apr 29 10:35:51 CST 2020
     */
    public Account withBitmask(Byte bitmask) {
        this.setBitmask(bitmask);
        return this;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ACCOUNT.BITMASK
     *
     * @param bitmask the value for ACCOUNT.BITMASK
     *
     * @mbg.generated Wed Apr 29 10:35:51 CST 2020
     */
    public void setBitmask(Byte bitmask) {
        this.bitmask = bitmask;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ACCOUNT.FORBIDTIME
     *
     * @return the value of ACCOUNT.FORBIDTIME
     *
     * @mbg.generated Wed Apr 29 10:35:51 CST 2020
     */
    public Integer getForbidtime() {
        return forbidtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ACCOUNT
     *
     * @mbg.generated Wed Apr 29 10:35:51 CST 2020
     */
    public Account withForbidtime(Integer forbidtime) {
        this.setForbidtime(forbidtime);
        return this;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ACCOUNT.FORBIDTIME
     *
     * @param forbidtime the value for ACCOUNT.FORBIDTIME
     *
     * @mbg.generated Wed Apr 29 10:35:51 CST 2020
     */
    public void setForbidtime(Integer forbidtime) {
        this.forbidtime = forbidtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ACCOUNT.LASTLOGINTIME
     *
     * @return the value of ACCOUNT.LASTLOGINTIME
     *
     * @mbg.generated Wed Apr 29 10:35:51 CST 2020
     */
    public String getLastlogintime() {
        return lastlogintime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ACCOUNT
     *
     * @mbg.generated Wed Apr 29 10:35:51 CST 2020
     */
    public Account withLastlogintime(String lastlogintime) {
        this.setLastlogintime(lastlogintime);
        return this;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ACCOUNT.LASTLOGINTIME
     *
     * @param lastlogintime the value for ACCOUNT.LASTLOGINTIME
     *
     * @mbg.generated Wed Apr 29 10:35:51 CST 2020
     */
    public void setLastlogintime(String lastlogintime) {
        this.lastlogintime = lastlogintime == null ? null : lastlogintime.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ACCOUNT.MOBILE
     *
     * @return the value of ACCOUNT.MOBILE
     *
     * @mbg.generated Wed Apr 29 10:35:51 CST 2020
     */
    public String getMobile() {
        return mobile;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ACCOUNT
     *
     * @mbg.generated Wed Apr 29 10:35:51 CST 2020
     */
    public Account withMobile(String mobile) {
        this.setMobile(mobile);
        return this;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ACCOUNT.MOBILE
     *
     * @param mobile the value for ACCOUNT.MOBILE
     *
     * @mbg.generated Wed Apr 29 10:35:51 CST 2020
     */
    public void setMobile(String mobile) {
        this.mobile = mobile == null ? null : mobile.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ACCOUNT.DEVSTRING
     *
     * @return the value of ACCOUNT.DEVSTRING
     *
     * @mbg.generated Wed Apr 29 10:35:51 CST 2020
     */
    public String getDevstring() {
        return devstring;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ACCOUNT
     *
     * @mbg.generated Wed Apr 29 10:35:51 CST 2020
     */
    public Account withDevstring(String devstring) {
        this.setDevstring(devstring);
        return this;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ACCOUNT.DEVSTRING
     *
     * @param devstring the value for ACCOUNT.DEVSTRING
     *
     * @mbg.generated Wed Apr 29 10:35:51 CST 2020
     */
    public void setDevstring(String devstring) {
        this.devstring = devstring == null ? null : devstring.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ACCOUNT.PACKAGEFLAG
     *
     * @return the value of ACCOUNT.PACKAGEFLAG
     *
     * @mbg.generated Wed Apr 29 10:35:51 CST 2020
     */
    public String getPackageflag() {
        return packageflag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ACCOUNT
     *
     * @mbg.generated Wed Apr 29 10:35:51 CST 2020
     */
    public Account withPackageflag(String packageflag) {
        this.setPackageflag(packageflag);
        return this;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ACCOUNT.PACKAGEFLAG
     *
     * @param packageflag the value for ACCOUNT.PACKAGEFLAG
     *
     * @mbg.generated Wed Apr 29 10:35:51 CST 2020
     */
    public void setPackageflag(String packageflag) {
        this.packageflag = packageflag == null ? null : packageflag.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ACCOUNT.LOGINPACKAGETYPE
     *
     * @return the value of ACCOUNT.LOGINPACKAGETYPE
     *
     * @mbg.generated Wed Apr 29 10:35:51 CST 2020
     */
    public Integer getLoginpackagetype() {
        return loginpackagetype;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ACCOUNT
     *
     * @mbg.generated Wed Apr 29 10:35:51 CST 2020
     */
    public Account withLoginpackagetype(Integer loginpackagetype) {
        this.setLoginpackagetype(loginpackagetype);
        return this;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ACCOUNT.LOGINPACKAGETYPE
     *
     * @param loginpackagetype the value for ACCOUNT.LOGINPACKAGETYPE
     *
     * @mbg.generated Wed Apr 29 10:35:51 CST 2020
     */
    public void setLoginpackagetype(Integer loginpackagetype) {
        this.loginpackagetype = loginpackagetype;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ACCOUNT.PACKAGETYPE
     *
     * @return the value of ACCOUNT.PACKAGETYPE
     *
     * @mbg.generated Wed Apr 29 10:35:51 CST 2020
     */
    public Integer getPackagetype() {
        return packagetype;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ACCOUNT
     *
     * @mbg.generated Wed Apr 29 10:35:51 CST 2020
     */
    public Account withPackagetype(Integer packagetype) {
        this.setPackagetype(packagetype);
        return this;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ACCOUNT.PACKAGETYPE
     *
     * @param packagetype the value for ACCOUNT.PACKAGETYPE
     *
     * @mbg.generated Wed Apr 29 10:35:51 CST 2020
     */
    public void setPackagetype(Integer packagetype) {
        this.packagetype = packagetype;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ACCOUNT.COUNTTYPE
     *
     * @return the value of ACCOUNT.COUNTTYPE
     *
     * @mbg.generated Wed Apr 29 10:35:51 CST 2020
     */
    public Integer getCounttype() {
        return counttype;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ACCOUNT
     *
     * @mbg.generated Wed Apr 29 10:35:51 CST 2020
     */
    public Account withCounttype(Integer counttype) {
        this.setCounttype(counttype);
        return this;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ACCOUNT.COUNTTYPE
     *
     * @param counttype the value for ACCOUNT.COUNTTYPE
     *
     * @mbg.generated Wed Apr 29 10:35:51 CST 2020
     */
    public void setCounttype(Integer counttype) {
        this.counttype = counttype;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ACCOUNT.REGIESTIP
     *
     * @return the value of ACCOUNT.REGIESTIP
     *
     * @mbg.generated Wed Apr 29 10:35:51 CST 2020
     */
    public String getRegiestip() {
        return regiestip;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ACCOUNT
     *
     * @mbg.generated Wed Apr 29 10:35:51 CST 2020
     */
    public Account withRegiestip(String regiestip) {
        this.setRegiestip(regiestip);
        return this;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ACCOUNT.REGIESTIP
     *
     * @param regiestip the value for ACCOUNT.REGIESTIP
     *
     * @mbg.generated Wed Apr 29 10:35:51 CST 2020
     */
    public void setRegiestip(String regiestip) {
        this.regiestip = regiestip == null ? null : regiestip.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ACCOUNT.LOGINDEVSTRING
     *
     * @return the value of ACCOUNT.LOGINDEVSTRING
     *
     * @mbg.generated Wed Apr 29 10:35:51 CST 2020
     */
    public String getLogindevstring() {
        return logindevstring;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ACCOUNT
     *
     * @mbg.generated Wed Apr 29 10:35:51 CST 2020
     */
    public Account withLogindevstring(String logindevstring) {
        this.setLogindevstring(logindevstring);
        return this;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ACCOUNT.LOGINDEVSTRING
     *
     * @param logindevstring the value for ACCOUNT.LOGINDEVSTRING
     *
     * @mbg.generated Wed Apr 29 10:35:51 CST 2020
     */
    public void setLogindevstring(String logindevstring) {
        this.logindevstring = logindevstring == null ? null : logindevstring.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ACCOUNT.LOGINPACKAGEFLAG
     *
     * @return the value of ACCOUNT.LOGINPACKAGEFLAG
     *
     * @mbg.generated Wed Apr 29 10:35:51 CST 2020
     */
    public String getLoginpackageflag() {
        return loginpackageflag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ACCOUNT
     *
     * @mbg.generated Wed Apr 29 10:35:51 CST 2020
     */
    public Account withLoginpackageflag(String loginpackageflag) {
        this.setLoginpackageflag(loginpackageflag);
        return this;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ACCOUNT.LOGINPACKAGEFLAG
     *
     * @param loginpackageflag the value for ACCOUNT.LOGINPACKAGEFLAG
     *
     * @mbg.generated Wed Apr 29 10:35:51 CST 2020
     */
    public void setLoginpackageflag(String loginpackageflag) {
        this.loginpackageflag = loginpackageflag == null ? null : loginpackageflag.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ACCOUNT.SPREADID
     *
     * @return the value of ACCOUNT.SPREADID
     *
     * @mbg.generated Wed Apr 29 10:35:51 CST 2020
     */
    public Integer getSpreadid() {
        return spreadid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ACCOUNT
     *
     * @mbg.generated Wed Apr 29 10:35:51 CST 2020
     */
    public Account withSpreadid(Integer spreadid) {
        this.setSpreadid(spreadid);
        return this;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ACCOUNT.SPREADID
     *
     * @param spreadid the value for ACCOUNT.SPREADID
     *
     * @mbg.generated Wed Apr 29 10:35:51 CST 2020
     */
    public void setSpreadid(Integer spreadid) {
        this.spreadid = spreadid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ACCOUNT.RegistTime
     *
     * @return the value of ACCOUNT.RegistTime
     *
     * @mbg.generated Wed Apr 29 10:35:51 CST 2020
     */
    public Long getRegisttime() {
        return registtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ACCOUNT
     *
     * @mbg.generated Wed Apr 29 10:35:51 CST 2020
     */
    public Account withRegisttime(Long registtime) {
        this.setRegisttime(registtime);
        return this;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ACCOUNT.RegistTime
     *
     * @param registtime the value for ACCOUNT.RegistTime
     *
     * @mbg.generated Wed Apr 29 10:35:51 CST 2020
     */
    public void setRegisttime(Long registtime) {
        this.registtime = registtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ACCOUNT.DEVICETYPE
     *
     * @return the value of ACCOUNT.DEVICETYPE
     *
     * @mbg.generated Wed Apr 29 10:35:51 CST 2020
     */
    public Integer getDevicetype() {
        return devicetype;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ACCOUNT
     *
     * @mbg.generated Wed Apr 29 10:35:51 CST 2020
     */
    public Account withDevicetype(Integer devicetype) {
        this.setDevicetype(devicetype);
        return this;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ACCOUNT.DEVICETYPE
     *
     * @param devicetype the value for ACCOUNT.DEVICETYPE
     *
     * @mbg.generated Wed Apr 29 10:35:51 CST 2020
     */
    public void setDevicetype(Integer devicetype) {
        this.devicetype = devicetype;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ACCOUNT.roletime
     *
     * @return the value of ACCOUNT.roletime
     *
     * @mbg.generated Wed Apr 29 10:35:51 CST 2020
     */
    public Long getRoletime() {
        return roletime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ACCOUNT
     *
     * @mbg.generated Wed Apr 29 10:35:51 CST 2020
     */
    public Account withRoletime(Long roletime) {
        this.setRoletime(roletime);
        return this;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ACCOUNT.roletime
     *
     * @param roletime the value for ACCOUNT.roletime
     *
     * @mbg.generated Wed Apr 29 10:35:51 CST 2020
     */
    public void setRoletime(Long roletime) {
        this.roletime = roletime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ACCOUNT.logindevinfo
     *
     * @return the value of ACCOUNT.logindevinfo
     *
     * @mbg.generated Wed Apr 29 10:35:51 CST 2020
     */
    public String getLogindevinfo() {
        return logindevinfo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ACCOUNT
     *
     * @mbg.generated Wed Apr 29 10:35:51 CST 2020
     */
    public Account withLogindevinfo(String logindevinfo) {
        this.setLogindevinfo(logindevinfo);
        return this;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ACCOUNT.logindevinfo
     *
     * @param logindevinfo the value for ACCOUNT.logindevinfo
     *
     * @mbg.generated Wed Apr 29 10:35:51 CST 2020
     */
    public void setLogindevinfo(String logindevinfo) {
        this.logindevinfo = logindevinfo == null ? null : logindevinfo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ACCOUNT.pversion
     *
     * @return the value of ACCOUNT.pversion
     *
     * @mbg.generated Wed Apr 29 10:35:51 CST 2020
     */
    public String getPversion() {
        return pversion;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ACCOUNT
     *
     * @mbg.generated Wed Apr 29 10:35:51 CST 2020
     */
    public Account withPversion(String pversion) {
        this.setPversion(pversion);
        return this;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ACCOUNT.pversion
     *
     * @param pversion the value for ACCOUNT.pversion
     *
     * @mbg.generated Wed Apr 29 10:35:51 CST 2020
     */
    public void setPversion(String pversion) {
        this.pversion = pversion == null ? null : pversion.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ACCOUNT.regversion
     *
     * @return the value of ACCOUNT.regversion
     *
     * @mbg.generated Wed Apr 29 10:35:51 CST 2020
     */
    public String getRegversion() {
        return regversion;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ACCOUNT
     *
     * @mbg.generated Wed Apr 29 10:35:51 CST 2020
     */
    public Account withRegversion(String regversion) {
        this.setRegversion(regversion);
        return this;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ACCOUNT.regversion
     *
     * @param regversion the value for ACCOUNT.regversion
     *
     * @mbg.generated Wed Apr 29 10:35:51 CST 2020
     */
    public void setRegversion(String regversion) {
        this.regversion = regversion == null ? null : regversion.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ACCOUNT
     *
     * @mbg.generated Wed Apr 29 10:35:51 CST 2020
     */
    @Override
    public boolean equals(Object that) {
        if (this == that) {
            return true;
        }
        if (that == null) {
            return false;
        }
        if (getClass() != that.getClass()) {
            return false;
        }
        Account other = (Account) that;
        return (this.getId() == null ? other.getId() == null : this.getId().equals(other.getId()))
            && (this.getAccid() == null ? other.getAccid() == null : this.getAccid().equals(other.getAccid()))
            && (this.getUsername() == null ? other.getUsername() == null : this.getUsername().equals(other.getUsername()))
            && (this.getPassword() == null ? other.getPassword() == null : this.getPassword().equals(other.getPassword()))
            && (this.getCreatetime() == null ? other.getCreatetime() == null : this.getCreatetime().equals(other.getCreatetime()))
            && (this.getBitmask() == null ? other.getBitmask() == null : this.getBitmask().equals(other.getBitmask()))
            && (this.getForbidtime() == null ? other.getForbidtime() == null : this.getForbidtime().equals(other.getForbidtime()))
            && (this.getLastlogintime() == null ? other.getLastlogintime() == null : this.getLastlogintime().equals(other.getLastlogintime()))
            && (this.getMobile() == null ? other.getMobile() == null : this.getMobile().equals(other.getMobile()))
            && (this.getDevstring() == null ? other.getDevstring() == null : this.getDevstring().equals(other.getDevstring()))
            && (this.getPackageflag() == null ? other.getPackageflag() == null : this.getPackageflag().equals(other.getPackageflag()))
            && (this.getLoginpackagetype() == null ? other.getLoginpackagetype() == null : this.getLoginpackagetype().equals(other.getLoginpackagetype()))
            && (this.getPackagetype() == null ? other.getPackagetype() == null : this.getPackagetype().equals(other.getPackagetype()))
            && (this.getCounttype() == null ? other.getCounttype() == null : this.getCounttype().equals(other.getCounttype()))
            && (this.getRegiestip() == null ? other.getRegiestip() == null : this.getRegiestip().equals(other.getRegiestip()))
            && (this.getLogindevstring() == null ? other.getLogindevstring() == null : this.getLogindevstring().equals(other.getLogindevstring()))
            && (this.getLoginpackageflag() == null ? other.getLoginpackageflag() == null : this.getLoginpackageflag().equals(other.getLoginpackageflag()))
            && (this.getSpreadid() == null ? other.getSpreadid() == null : this.getSpreadid().equals(other.getSpreadid()))
            && (this.getRegisttime() == null ? other.getRegisttime() == null : this.getRegisttime().equals(other.getRegisttime()))
            && (this.getDevicetype() == null ? other.getDevicetype() == null : this.getDevicetype().equals(other.getDevicetype()))
            && (this.getRoletime() == null ? other.getRoletime() == null : this.getRoletime().equals(other.getRoletime()))
            && (this.getLogindevinfo() == null ? other.getLogindevinfo() == null : this.getLogindevinfo().equals(other.getLogindevinfo()))
            && (this.getPversion() == null ? other.getPversion() == null : this.getPversion().equals(other.getPversion()))
            && (this.getRegversion() == null ? other.getRegversion() == null : this.getRegversion().equals(other.getRegversion()));
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ACCOUNT
     *
     * @mbg.generated Wed Apr 29 10:35:51 CST 2020
     */
    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((getId() == null) ? 0 : getId().hashCode());
        result = prime * result + ((getAccid() == null) ? 0 : getAccid().hashCode());
        result = prime * result + ((getUsername() == null) ? 0 : getUsername().hashCode());
        result = prime * result + ((getPassword() == null) ? 0 : getPassword().hashCode());
        result = prime * result + ((getCreatetime() == null) ? 0 : getCreatetime().hashCode());
        result = prime * result + ((getBitmask() == null) ? 0 : getBitmask().hashCode());
        result = prime * result + ((getForbidtime() == null) ? 0 : getForbidtime().hashCode());
        result = prime * result + ((getLastlogintime() == null) ? 0 : getLastlogintime().hashCode());
        result = prime * result + ((getMobile() == null) ? 0 : getMobile().hashCode());
        result = prime * result + ((getDevstring() == null) ? 0 : getDevstring().hashCode());
        result = prime * result + ((getPackageflag() == null) ? 0 : getPackageflag().hashCode());
        result = prime * result + ((getLoginpackagetype() == null) ? 0 : getLoginpackagetype().hashCode());
        result = prime * result + ((getPackagetype() == null) ? 0 : getPackagetype().hashCode());
        result = prime * result + ((getCounttype() == null) ? 0 : getCounttype().hashCode());
        result = prime * result + ((getRegiestip() == null) ? 0 : getRegiestip().hashCode());
        result = prime * result + ((getLogindevstring() == null) ? 0 : getLogindevstring().hashCode());
        result = prime * result + ((getLoginpackageflag() == null) ? 0 : getLoginpackageflag().hashCode());
        result = prime * result + ((getSpreadid() == null) ? 0 : getSpreadid().hashCode());
        result = prime * result + ((getRegisttime() == null) ? 0 : getRegisttime().hashCode());
        result = prime * result + ((getDevicetype() == null) ? 0 : getDevicetype().hashCode());
        result = prime * result + ((getRoletime() == null) ? 0 : getRoletime().hashCode());
        result = prime * result + ((getLogindevinfo() == null) ? 0 : getLogindevinfo().hashCode());
        result = prime * result + ((getPversion() == null) ? 0 : getPversion().hashCode());
        result = prime * result + ((getRegversion() == null) ? 0 : getRegversion().hashCode());
        return result;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ACCOUNT
     *
     * @mbg.generated Wed Apr 29 10:35:51 CST 2020
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", id=").append(id);
        sb.append(", accid=").append(accid);
        sb.append(", username=").append(username);
        sb.append(", password=").append(password);
        sb.append(", createtime=").append(createtime);
        sb.append(", bitmask=").append(bitmask);
        sb.append(", forbidtime=").append(forbidtime);
        sb.append(", lastlogintime=").append(lastlogintime);
        sb.append(", mobile=").append(mobile);
        sb.append(", devstring=").append(devstring);
        sb.append(", packageflag=").append(packageflag);
        sb.append(", loginpackagetype=").append(loginpackagetype);
        sb.append(", packagetype=").append(packagetype);
        sb.append(", counttype=").append(counttype);
        sb.append(", regiestip=").append(regiestip);
        sb.append(", logindevstring=").append(logindevstring);
        sb.append(", loginpackageflag=").append(loginpackageflag);
        sb.append(", spreadid=").append(spreadid);
        sb.append(", registtime=").append(registtime);
        sb.append(", devicetype=").append(devicetype);
        sb.append(", roletime=").append(roletime);
        sb.append(", logindevinfo=").append(logindevinfo);
        sb.append(", pversion=").append(pversion);
        sb.append(", regversion=").append(regversion);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}