package com.leo.domain;

import java.io.Serializable;

public class RoleKey implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column role.seqid
     *
     * @mbg.generated Wed Apr 29 10:35:51 CST 2020
     */
    private Integer seqid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column role.no
     *
     * @mbg.generated Wed Apr 29 10:35:51 CST 2020
     */
    private String no;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table role
     *
     * @mbg.generated Wed Apr 29 10:35:51 CST 2020
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column role.seqid
     *
     * @return the value of role.seqid
     *
     * @mbg.generated Wed Apr 29 10:35:51 CST 2020
     */
    public Integer getSeqid() {
        return seqid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table role
     *
     * @mbg.generated Wed Apr 29 10:35:51 CST 2020
     */
    public RoleKey withSeqid(Integer seqid) {
        this.setSeqid(seqid);
        return this;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column role.seqid
     *
     * @param seqid the value for role.seqid
     *
     * @mbg.generated Wed Apr 29 10:35:51 CST 2020
     */
    public void setSeqid(Integer seqid) {
        this.seqid = seqid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column role.no
     *
     * @return the value of role.no
     *
     * @mbg.generated Wed Apr 29 10:35:51 CST 2020
     */
    public String getNo() {
        return no;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table role
     *
     * @mbg.generated Wed Apr 29 10:35:51 CST 2020
     */
    public RoleKey withNo(String no) {
        this.setNo(no);
        return this;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column role.no
     *
     * @param no the value for role.no
     *
     * @mbg.generated Wed Apr 29 10:35:51 CST 2020
     */
    public void setNo(String no) {
        this.no = no == null ? null : no.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table role
     *
     * @mbg.generated Wed Apr 29 10:35:51 CST 2020
     */
    @Override
    public boolean equals(Object that) {
        if (this == that) {
            return true;
        }
        if (that == null) {
            return false;
        }
        if (getClass() != that.getClass()) {
            return false;
        }
        RoleKey other = (RoleKey) that;
        return (this.getSeqid() == null ? other.getSeqid() == null : this.getSeqid().equals(other.getSeqid()))
            && (this.getNo() == null ? other.getNo() == null : this.getNo().equals(other.getNo()));
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table role
     *
     * @mbg.generated Wed Apr 29 10:35:51 CST 2020
     */
    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((getSeqid() == null) ? 0 : getSeqid().hashCode());
        result = prime * result + ((getNo() == null) ? 0 : getNo().hashCode());
        return result;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table role
     *
     * @mbg.generated Wed Apr 29 10:35:51 CST 2020
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", seqid=").append(seqid);
        sb.append(", no=").append(no);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}