package com.leo.domain;

public class RoleKey {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column role.seqid
     *
     * @mbg.generated
     */
    private Long seqid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column role.no
     *
     * @mbg.generated
     */
    private String no;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column role.seqid
     *
     * @return the value of role.seqid
     *
     * @mbg.generated
     */
    public Long getSeqid() {
        return seqid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column role.seqid
     *
     * @param seqid the value for role.seqid
     *
     * @mbg.generated
     */
    public void setSeqid(Long seqid) {
        this.seqid = seqid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column role.no
     *
     * @return the value of role.no
     *
     * @mbg.generated
     */
    public String getNo() {
        return no;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column role.no
     *
     * @param no the value for role.no
     *
     * @mbg.generated
     */
    public void setNo(String no) {
        this.no = no == null ? null : no.trim();
    }
}