package com.leo.domain;

public class User {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.id
     *
     * @mbg.generated Sat Oct 27 11:29:39 CST 2018
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.name
     *
     * @mbg.generated Sat Oct 27 11:29:39 CST 2018
     */
    private String name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.NEXTVIPLEVEL
     *
     * @mbg.generated Sat Oct 27 11:29:39 CST 2018
     */
    private Integer nextviplevel;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.NEXTVIPEXP
     *
     * @mbg.generated Sat Oct 27 11:29:39 CST 2018
     */
    private Long nextvipexp;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.id
     *
     * @return the value of user.id
     *
     * @mbg.generated Sat Oct 27 11:29:39 CST 2018
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.id
     *
     * @param id the value for user.id
     *
     * @mbg.generated Sat Oct 27 11:29:39 CST 2018
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.name
     *
     * @return the value of user.name
     *
     * @mbg.generated Sat Oct 27 11:29:39 CST 2018
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.name
     *
     * @param name the value for user.name
     *
     * @mbg.generated Sat Oct 27 11:29:39 CST 2018
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.NEXTVIPLEVEL
     *
     * @return the value of user.NEXTVIPLEVEL
     *
     * @mbg.generated Sat Oct 27 11:29:39 CST 2018
     */
    public Integer getNextviplevel() {
        return nextviplevel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.NEXTVIPLEVEL
     *
     * @param nextviplevel the value for user.NEXTVIPLEVEL
     *
     * @mbg.generated Sat Oct 27 11:29:39 CST 2018
     */
    public void setNextviplevel(Integer nextviplevel) {
        this.nextviplevel = nextviplevel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.NEXTVIPEXP
     *
     * @return the value of user.NEXTVIPEXP
     *
     * @mbg.generated Sat Oct 27 11:29:39 CST 2018
     */
    public Long getNextvipexp() {
        return nextvipexp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.NEXTVIPEXP
     *
     * @param nextvipexp the value for user.NEXTVIPEXP
     *
     * @mbg.generated Sat Oct 27 11:29:39 CST 2018
     */
    public void setNextvipexp(Long nextvipexp) {
        this.nextvipexp = nextvipexp;
    }
}